# Generated by Django 4.1.4 on 2022-12-26 18:03

from django.db import migrations
import treasuremap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='point',
            field=treasuremap.fields.LatLongField(blank=True, max_length=24),
        ),
    ]
