# Generated by Django 4.1.4 on 2022-12-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_post_lonlatstr_alter_post_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lonlatstr',
            field=models.CharField(max_length=255, verbose_name='Для запроса'),
        ),
    ]
